language: java

sudo: required
dist: trusty

matrix:
  include:
  - jdk: oraclejdk8
    env: BUILD_JDK=ORACLE_JDK_8

# https://docs.travis-ci.com/user/languages/java/#maven-dependency-management
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DminimumPriority=1

cache:
  directories:
  - $HOME/.m2/
